In [1]:
import numpy as np

In [2]:

arr = np.array([1, 2, 3, 4], dtype=np.float64)

In [3]:
print(f'{arr.shape}')
print(arr.dtype)
print(arr.ndim)
print(arr
      .size)
print(arr)

(4,)
float64
1
4
[1. 2. 3. 4.]


In [4]:
arr = np.ones((2, 3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.arange(0, 10, 0.5, dtype=np.float64)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [20]:
arr = np.linspace(0, 6, num=21, dtype=np.float64)
arr

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7, 6. ])

In [18]:
arr.astype(np.int64)

array([0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6])

In [16]:
np.empty((2, 3, 3))

array([[[1.51558634e-316, 0.00000000e+000, 6.12141097e-310],
        [6.12141097e-310, 6.12141097e-310, 6.12141097e-310],
        [6.12141097e-310, 6.12141097e-310, 6.12141097e-310]],

       [[6.12141097e-310, 6.12141097e-310, 6.12141097e-310],
        [6.12141097e-310, 6.12141097e-310, 6.12141097e-310],
        [6.12141097e-310, 6.12141097e-310, 6.12141097e-310]]])

In [22]:
np.reshape(arr, (3, 7))


array([[0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8],
       [2.1, 2.4, 2.7, 3. , 3.3, 3.6, 3.9],
       [4.2, 4.5, 4.8, 5.1, 5.4, 5.7, 6. ]])

In [36]:
rng = np.random.default_rng()
rng.standard_normal((2, 3))

array([[ 1.39956639,  0.22652026,  0.24278483],
       [-0.05312508,  0.66737861, -0.06432593]])

In [93]:
#arr = np.arange(1, 13, 1).reshape(2, 2, 3)
arr = np.arange(1, 25, 1).reshape(3, 2, 4)


In [94]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [97]:
arr[1, :, 1:3].shape

(2, 2)

In [103]:
arr = np.random.randn(2, 3)

In [104]:
arr

array([[ 1.08176782e+00, -9.88744052e-01,  9.07071503e-04],
       [-6.68244429e-02, -9.45144327e-01,  6.64241373e-02]])

In [105]:
arr < 0

array([[False,  True, False],
       [ True,  True, False]])

In [106]:
arr[arr<0].shape

(3,)

In [107]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Henry", "Will", "Matt"])

In [108]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [110]:
arr = np.random.randn(7, 4) 
arr

array([[ 0.58789652,  2.08139464,  1.5608841 ,  2.12885675],
       [-1.88469053,  0.41512657,  1.62204397,  0.43979452],
       [-0.29621396, -1.09018962, -0.2369001 , -0.55428327],
       [-1.03972336,  0.06664559, -0.21286953, -1.36794122],
       [ 0.54852535,  0.41414849,  0.22261525, -0.13181781],
       [ 2.37343818,  0.50792256, -0.48387882, -0.00768293],
       [ 0.78502352,  0.34573973,  1.17316116,  0.49708119]])

In [120]:
arr[1:3, 0].shape

(2,)

In [122]:
arr = np.arange(10, 0, -1) 
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [126]:
arr[np.array([[0, 1], [0, 1]])]

array([[10,  9],
       [10,  9]])

In [128]:
arr = np.arange(24).reshape(2, 3, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [131]:
arr[np.array([0, 1, 1]), np.array([1, 2, 1]), np.array([1, 2, 3])].shape

(3,)

In [138]:
arr_indexed = arr[np.array([0, 1, 1]), np.array([1, 2, 1])]
arr_indexed

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [16, 17, 18, 19]])

In [139]:
arr_indexed[:] = 0


In [141]:
arr
#arr_indexed

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [144]:
arr_indexed = arr[np.array([0, 1, 1]), [0, 2], 3]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [143]:
arr_indexed

array([11, 23, 23])

In [145]:
rng = np.random.default_rng()
arr = rng.standard_normal((7, 4))
arr

array([[-0.77790687, -0.72662062, -2.03107631, -2.03987679],
       [ 2.07057823, -0.04199792,  0.10140466, -0.88617013],
       [-0.93374722, -2.76092072, -0.55573462, -0.68438273],
       [ 0.58597968,  1.2080812 ,  0.29081551,  0.74137408],
       [-0.22334866,  1.82240807,  0.46266871, -0.19841311],
       [-1.90197375,  1.28513776,  0.79456649,  0.64744116],
       [ 0.21739798, -1.46741487, -1.00200072,  0.67573917]])

In [146]:
boolArr = rng.choice([True, False], (7,))

In [147]:
boolArr

array([False, False,  True, False,  True, False, False])

In [148]:
arr_indexed = arr[boolArr]

In [149]:
arr_indexed.shape

(2, 4)

In [150]:
arr_indexed

array([[-0.93374722, -2.76092072, -0.55573462, -0.68438273],
       [-0.22334866,  1.82240807,  0.46266871, -0.19841311]])

In [151]:
arr = np.arange(1, 13, 1).reshape(2, 2, 3)

In [152]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [153]:
arr1d = np.array([0, 1, 2])

In [154]:
arr + arr1d

array([[[ 1,  3,  5],
        [ 4,  6,  8]],

       [[ 7,  9, 11],
        [10, 12, 14]]])

In [155]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

In [163]:
x = a[:, np.newaxis]

In [164]:
x.shape

(4, 1)

In [165]:
b.shape

(3,)

In [166]:
x + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])