In [25]:
# KNN classification --> probably the easiest one
# Step 1: Choose a value for K, Usually K=5
# Step 2: Find the K nearest neighbors from your test data point using Euclidean distance
# Step 3: Count which category each of the K neighbors belong to
# Step 4: Assign the new data point to thte category where you counted the most neighbors.
# Step 5: done

In [26]:
import numpy as np
import pandas as pd
from pandas import DataFrame
import matplotlib.pyplot as plt
import matplotlib as mpl
from sklearn.model_selection import train_test_split

In [27]:
dataset = pd.read_csv('MachineLearningAZ/Part3_Classification/Section15_KNN/Python/Social_Network_Ads.csv')

In [28]:
dataset

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [29]:
%matplotlib inline

In [30]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [31]:
print(X)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [32]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
sc_X = StandardScaler()

In [36]:
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [37]:
print(X_train)

[[ 1.92e+00  2.15e+00]
 [ 2.02e+00  3.79e-01]
 [-1.38e+00 -4.32e-01]
 [-1.19e+00 -1.01e+00]
 [ 1.92e+00 -9.25e-01]
 [ 3.68e-01  2.92e-01]
 [ 1.73e-01  1.47e-01]
 [ 2.02e+00  1.74e+00]
 [ 7.56e-01 -8.38e-01]
 [ 2.70e-01 -2.88e-01]
 [ 3.68e-01 -1.72e-01]
 [-1.18e-01  2.20e+00]
 [-1.48e+00 -6.35e-01]
 [-1.29e+00 -1.07e+00]
 [-1.38e+00  4.08e-01]
 [-1.09e+00  7.55e-01]
 [-1.48e+00 -2.01e-01]
 [ 9.51e-01 -1.07e+00]
 [ 9.51e-01  5.82e-01]
 [ 3.68e-01  9.87e-01]
 [ 5.62e-01 -8.96e-01]
 [-6.05e-01  1.45e+00]
 [-2.13e-02 -5.77e-01]
 [-6.05e-01  1.89e+00]
 [ 1.34e+00 -1.42e+00]
 [ 1.44e+00  9.87e-01]
 [ 7.59e-02 -8.09e-01]
 [-2.13e-02 -2.59e-01]
 [-2.16e-01 -5.77e-01]
 [-2.16e-01 -2.01e-01]
 [-3.13e-01 -1.30e+00]
 [-3.13e-01 -5.77e-01]
 [ 3.68e-01  8.90e-02]
 [ 8.54e-01 -6.06e-01]
 [ 2.02e+00 -1.19e+00]
 [ 1.05e+00 -1.43e-01]
 [ 6.59e-01  1.77e+00]
 [-7.02e-01  5.53e-01]
 [ 7.56e-01  3.50e-01]
 [ 8.54e-01 -5.48e-01]
 [-1.19e+00 -1.59e+00]
 [ 2.12e+00  9.29e-01]
 [-2.13e-02  1.22e+00]
 [ 1.73e-01

In [38]:
print(X_test)

[[-7.99e-01  4.95e-01]
 [-2.13e-02 -5.77e-01]
 [-3.13e-01  1.47e-01]
 [-7.99e-01  2.63e-01]
 [-3.13e-01 -5.77e-01]
 [-1.09e+00 -1.45e+00]
 [-7.02e-01 -1.59e+00]
 [-2.16e-01  2.15e+00]
 [-1.97e+00 -5.59e-02]
 [ 8.54e-01 -7.80e-01]
 [-7.99e-01 -6.06e-01]
 [-9.93e-01 -4.32e-01]
 [-1.18e-01 -4.32e-01]
 [ 7.59e-02  2.05e-01]
 [-1.77e+00  4.66e-01]
 [-6.05e-01  1.36e+00]
 [-1.18e-01  2.05e-01]
 [-1.87e+00  4.37e-01]
 [ 1.63e+00  1.74e+00]
 [-3.13e-01 -1.39e+00]
 [-3.13e-01 -6.64e-01]
 [ 8.54e-01  2.15e+00]
 [ 2.70e-01 -5.48e-01]
 [ 8.54e-01  1.02e+00]
 [-1.48e+00 -1.21e+00]
 [ 1.05e+00  2.06e+00]
 [-9.93e-01  4.95e-01]
 [-8.96e-01  2.92e-01]
 [-1.18e-01 -2.30e-01]
 [-6.05e-01  4.66e-01]
 [-1.67e+00  5.24e-01]
 [-1.18e-01  2.63e-01]
 [ 1.83e+00 -2.88e-01]
 [-1.18e-01 -4.90e-01]
 [-1.38e+00 -3.46e-01]
 [-1.97e+00 -5.19e-01]
 [-1.58e+00  3.21e-01]
 [-4.10e-01 -7.80e-01]
 [-7.02e-01 -1.04e+00]
 [ 1.05e+00 -9.83e-01]
 [-1.09e+00  5.24e-01]
 [ 2.70e-01 -5.19e-01]
 [-1.09e+00  4.08e-01]
 [-3.13e-01

In [39]:
# import KNN Classifier
from sklearn.neighbors import KNeighborsClassifier

In [40]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)

In [41]:
classifier = classifier.fit(X_train, y_train)

In [42]:
classifier.predict(sc_X.transform([[30, 87000]]))

array([0])

In [43]:
y_pred = classifier.predict(X_test)

In [44]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), axis=1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]


In [45]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [46]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[55,  3],
       [ 1, 21]])

In [47]:
accuracy_score(y_test, y_pred)

0.95

In [ ]:
# Visualising the Training set results
from matplotlib.colors import ListedColormap
sc = sc_X
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Logistic Regression (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

In [ ]:
# Visualize test set results
from matplotlib.colors import ListedColormap
sc = sc_X
X_set, y_set = sc.inverse_transform(X_test), y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Logistic Regression (Test set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()