In [4]:
# Data Preprocessing
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
# Importing DataSet
dataset = pd.read_csv('MachineLearningA-ZTemplateFolder/Part1_DataPreprocessing/Data.csv')

In [6]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [51]:
# Use iloc to separate features and labels
X = dataset.iloc[:, :-1].values  # iloc is used to address DataFrame using rows and columns

In [52]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [53]:
y = dataset.iloc[:, 3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'], dtype=object)

In [54]:
# Handling missing data
# 1. Either remove the complete row, which could be very dangerous as you might remove very important training data in the other columns
# 2. Replace missing data by the mean of the data for that column We'll do step 2

In [55]:
from sklearn.preprocessing import Imputer

In [56]:
# The Imputer class provides basic strategies for imputing missing values, either using the mean, the median
# or the most frequent value of the row or column in which the missing values are located. This class also allows
# for different missing values encodings.
imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)
# Apply the imputer using the fit function. ie, the mean values will be cacluated based on X[:, 1:3].values
imputer = imputer.fit(X[:, 1:3])

In [57]:
# Finally impute using transform, transform also takes a parameter of what to impute. impute(mean, median, mode) values 
# are already computed at the fit() step
X[:, 1:3] = imputer.transform(X[:, 1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [58]:
# Next, we need to encode categorical data to quantitative data ie columns like Country and Purchased.

In [59]:
from sklearn.preprocessing import LabelEncoder
le_X = LabelEncoder()

In [60]:
# Fit the labels, ie let the LabelEncoder know about the labels
le_X.fit(X[:, 0])

# View the labels
print(le_X.classes_)

['France' 'Germany' 'Spain']


In [61]:
# Now transform
le_X.transform(X[:, 0])

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

In [62]:
# Inverse_transform
le_X.inverse_transform([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

array(['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France', 'Spain',
       'France', 'Germany', 'France'], dtype=object)

In [63]:
# You can also fit and transform in the same step
le_X = LabelEncoder()
X[:, 0] = le_X.fit_transform(X[:, 0])

In [64]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [65]:
# Big Problem Above, The countries values are encoded as 0, 1, 2. This will make ML algo's think that these values 
# are comparable, ie 0(France) is less than 2(Spain) and 1(Germany) is greater than 0(France). If these were some
# other categorical data like size of shirts (Small, Medium, Large), it would have made sense, but here it doesnt
# make sense. To solve this, after we convert categorical data to quantitative, we have to separate the Countries
# into 3 columns (ie into as many columns as many country
# names). The value in these three column will be binary 0 or 1. So wherever the original country is France, the
# France column will have value 1 or other columns will have value 0. We use another Encoder for that next called
# OneHotEncoder

In [66]:
from sklearn.preprocessing import OneHotEncoder

In [67]:
ohe = OneHotEncoder(categorical_features=[0])

In [68]:
X = ohe.fit_transform(X)

In [70]:
X = X.toarray()

In [71]:
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.40000000e+01,   7.20000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          2.70000000e+01,   4.80000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          3.00000000e+01,   5.40000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.80000000e+01,   6.10000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          4.00000000e+01,   6.37777778e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          3.50000000e+01,   5.80000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.87777778e+01,   5.20000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.80000000e+01,   7.90000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          5.00000000e+01,   8.30000000e+04],
       [  1.00000000e+00,   0.0000000

In [72]:
# Lets encode the label to also quantitative data. We dont need OneHotEncoder as ML algo already know that Labels
# are unrelated so it never compares them.
le_y = LabelEncoder()
y = le_y.fit_transform(y)

In [73]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])